// This file is generated by Tools/cases_generator/wasm_generator.py
// from:
//   Python/bytecodes.c
// Do not edit!
struct two_values { PyObject *first; PyObject *second; };

------------------------
OPCODE: NOP
PROPERTIES:
   escapes: False
   error_with_pop: False
   error_without_pop: False
   deopts: False
   oparg: False
   jumps: False
   eval_breaker: False
   ends_with_eval_breaker: False
   needs_this: False
   always_exits: False
   stores_sp: False
   uses_co_consts: False
   uses_co_names: False
   uses_locals: False
   has_free: False
   side_exit: False
   pure: True
   tier: None
   oparg_and_1: False
   const_oparg: -1

Wasm import

(import "python" "handler_NOP" (func $handler_NOP (param) (result)))

C function

__attribute__ ((export_name("handler_NOP")))
void handler_NOP(void);

void handler_NOP(void) {
    // (matthew) begin emitting space for return
    // (matthew) end emitting space for return



    // (matthew) begin return
}

------------------------
OPCODE: LOAD_FAST
PROPERTIES:
   escapes: False
   error_with_pop: False
   error_without_pop: False
   deopts: False
   oparg: True
   jumps: False
   eval_breaker: False
   ends_with_eval_breaker: False
   needs_this: False
   always_exits: False
   stores_sp: False
   uses_co_consts: False
   uses_co_names: False
   uses_locals: True
   has_free: False
   side_exit: False
   pure: True
   tier: None
   oparg_and_1: False
   const_oparg: -1

Wasm import

(import "python" "handler_LOAD_FAST" (func $handler_LOAD_FAST (param i32) (result i32)))

C function

__attribute__ ((export_name("handler_LOAD_FAST")))
PyObject *handler_LOAD_FAST(int oparg);

PyObject *handler_LOAD_FAST(int oparg) {
    // (matthew) begin emitting space for return
    PyObject *value;
    // (matthew) end emitting space for return

    value = GETLOCAL(oparg);
    assert(value != NULL);
    Py_INCREF(value);

    // (matthew) begin return
    return value;
}

------------------------
OPCODE: POP_TOP
PROPERTIES:
   escapes: False
   error_with_pop: False
   error_without_pop: False
   deopts: False
   oparg: False
   jumps: False
   eval_breaker: False
   ends_with_eval_breaker: False
   needs_this: False
   always_exits: False
   stores_sp: False
   uses_co_consts: False
   uses_co_names: False
   uses_locals: False
   has_free: False
   side_exit: False
   pure: True
   tier: None
   oparg_and_1: False
   const_oparg: -1

Wasm import

(import "python" "handler_POP_TOP" (func $handler_POP_TOP (param i32) (result)))

C function

__attribute__ ((export_name("handler_POP_TOP")))
void handler_POP_TOP(PyObject *value);

void handler_POP_TOP(PyObject *value) {
    // (matthew) begin emitting space for return
    // (matthew) end emitting space for return

    Py_DECREF(value);


    // (matthew) begin return
}

------------------------
OPCODE: PUSH_NULL
PROPERTIES:
   escapes: False
   error_with_pop: False
   error_without_pop: False
   deopts: False
   oparg: False
   jumps: False
   eval_breaker: False
   ends_with_eval_breaker: False
   needs_this: False
   always_exits: False
   stores_sp: False
   uses_co_consts: False
   uses_co_names: False
   uses_locals: False
   has_free: False
   side_exit: False
   pure: True
   tier: None
   oparg_and_1: False
   const_oparg: -1

Wasm import

(import "python" "handler_PUSH_NULL" (func $handler_PUSH_NULL (param) (result i32)))

C function

__attribute__ ((export_name("handler_PUSH_NULL")))
PyObject *handler_PUSH_NULL(void);

PyObject *handler_PUSH_NULL(void) {
    // (matthew) begin emitting space for return
    PyObject *res;
    // (matthew) end emitting space for return

    res = NULL;

    // (matthew) begin return
    return res;
}

------------------------
OPCODE: END_SEND
PROPERTIES:
   escapes: False
   error_with_pop: False
   error_without_pop: False
   deopts: False
   oparg: False
   jumps: False
   eval_breaker: False
   ends_with_eval_breaker: False
   needs_this: False
   always_exits: False
   stores_sp: False
   uses_co_consts: False
   uses_co_names: False
   uses_locals: False
   has_free: False
   side_exit: False
   pure: True
   tier: None
   oparg_and_1: False
   const_oparg: -1

Wasm import

(import "python" "handler_END_SEND" (func $handler_END_SEND (param i32 i32) (result i32)))

C function

__attribute__ ((export_name("handler_END_SEND")))
PyObject *handler_END_SEND(PyObject *receiver, PyObject *value);

PyObject *handler_END_SEND(PyObject *receiver, PyObject *value) {
    // (matthew) begin emitting space for return
    // (matthew) end emitting space for return

    Py_DECREF(receiver);

    // (matthew) begin return
    return value;
}

------------------------
OPCODE: UNARY_NOT
PROPERTIES:
   escapes: False
   error_with_pop: False
   error_without_pop: False
   deopts: False
   oparg: False
   jumps: False
   eval_breaker: False
   ends_with_eval_breaker: False
   needs_this: False
   always_exits: False
   stores_sp: False
   uses_co_consts: False
   uses_co_names: False
   uses_locals: False
   has_free: False
   side_exit: False
   pure: True
   tier: None
   oparg_and_1: False
   const_oparg: -1

Wasm import

(import "python" "handler_UNARY_NOT" (func $handler_UNARY_NOT (param i32) (result i32)))

C function

__attribute__ ((export_name("handler_UNARY_NOT")))
PyObject *handler_UNARY_NOT(PyObject *value);

PyObject *handler_UNARY_NOT(PyObject *value) {
    // (matthew) begin emitting space for return
    PyObject *res;
    // (matthew) end emitting space for return

    assert(PyBool_Check(value));
    res = Py_IsFalse(value) ? Py_True : Py_False;

    // (matthew) begin return
    return res;
}

------------------------
OPCODE: COPY
PROPERTIES:
   escapes: False
   error_with_pop: False
   error_without_pop: False
   deopts: False
   oparg: True
   jumps: False
   eval_breaker: False
   ends_with_eval_breaker: False
   needs_this: False
   always_exits: False
   stores_sp: False
   uses_co_consts: False
   uses_co_names: False
   uses_locals: False
   has_free: False
   side_exit: False
   pure: True
   tier: None
   oparg_and_1: False
   const_oparg: -1

Wasm import

(import "python" "handler_COPY" (func $handler_COPY (param i32 i32 i32) (result i32 i32 i32)))

C function

>>#!@#@! SKIPPING because there are more than 2 outputs

------------------------
OPCODE: SWAP
PROPERTIES:
   escapes: False
   error_with_pop: False
   error_without_pop: False
   deopts: False
   oparg: True
   jumps: False
   eval_breaker: False
   ends_with_eval_breaker: False
   needs_this: False
   always_exits: False
   stores_sp: False
   uses_co_consts: False
   uses_co_names: False
   uses_locals: False
   has_free: False
   side_exit: False
   pure: True
   tier: None
   oparg_and_1: False
   const_oparg: -1

Wasm import

(import "python" "handler_SWAP" (func $handler_SWAP (param i32 i32 i32 i32) (result i32 i32 i32)))

C function

>>#!@#@! SKIPPING because there are more than 2 outputs

------------------------
OPCODE: END_FOR
PROPERTIES:
   escapes: False
   error_with_pop: False
   error_without_pop: False
   deopts: False
   oparg: False
   jumps: False
   eval_breaker: False
   ends_with_eval_breaker: False
   needs_this: False
   always_exits: False
   stores_sp: False
   uses_co_consts: False
   uses_co_names: False
   uses_locals: False
   has_free: False
   side_exit: False
   pure: True
   tier: None
   oparg_and_1: False
   const_oparg: -1

Wasm import

(import "python" "handler_POP_TOP" (func $handler_POP_TOP (param i32) (result)))

C function

__attribute__ ((export_name("handler_POP_TOP")))
void handler_POP_TOP(PyObject *value);

void handler_POP_TOP(PyObject *value) {
    // (matthew) begin emitting space for return
    // (matthew) end emitting space for return

    Py_DECREF(value);


    // (matthew) begin return
}
