// This file is generated by Tools/cases_generator/wasm_generator.py
// from:
//   Python/bytecodes.c
// Do not edit!

Wasm import

(import "python" "handler_NOP" (func $handler_NOP (param) (result)))

C function

__attribute__ ((export_name("handler_NOP")))
void handler_NOP(void);

void handler_NOP(void) {

}

Wasm import

(import "python" "handler_LOAD_FAST" (func $handler_LOAD_FAST (param) (result i32)))

C function

__attribute__ ((export_name("handler_LOAD_FAST")))
PyObject *handler_LOAD_FAST(void);

PyObject *handler_LOAD_FAST(void) {
    PyObject *value;

    value = GETLOCAL(oparg);
    assert(value != NULL);
    Py_INCREF(value);return value;

}

Wasm import

(import "python" "handler_STORE_FAST" (func $handler_STORE_FAST (param i32) (result)))

C function

__attribute__ ((export_name("handler_STORE_FAST")))
void handler_STORE_FAST(PyObject *value);

void handler_STORE_FAST(PyObject *value) {
    value = stack_pointer[-1];
    SETLOCAL(oparg, value);
}
